#!/usr/bin/env bash
# Regenerate PATCHES.md from the commits carried on top of the upstream base.
#
# The base is the upstream commit named in nexus/BASE (first field: full sha; the rest is a
# human note). It is a commit rather than a tag because the series follows upstream `develop`
# until the release that contains what we need exists; when it does, BASE moves to that tag.
#
# The register is derived from git, never edited by hand: each carried commit must end with an
# Upstream-Status trailer (Pending | Submitted [url] | Backport [#pr] | Denied | Inappropriate [reason]),
# and this script refuses to write the file if one is missing or malformed. The release workflow
# runs it and fails if the checked-in PATCHES.md is stale.
#
# No commit hashes in the table: they change on every rebase, and the commit that carries this
# file cannot know its own. Rows are the commit subjects, in series order.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

upstream=https://github.com/IHTSDO/snowstorm
base=$(awk '{print $1}' nexus/BASE)
base_note=$(cut -d' ' -f2- nexus/BASE)
git merge-base --is-ancestor "$base" HEAD || { echo "error: base $base from nexus/BASE is not an ancestor of HEAD" >&2; exit 1; }
commits=$(git rev-list --reverse "$base..HEAD")
count=$(printf '%s\n' "$commits" | grep -c . || true)

status_re='^(Pending|Submitted \[[^]]+\]|Backport \[[^]]+\]|Denied|Inappropriate \[[^]]+\])$'
{
  echo "# Patches carried by the Nexus EMR fork"
  echo
  echo "Base: upstream [IHTSDO/snowstorm]($upstream) commit [\`${base:0:8}\`]($upstream/commit/$base), $base_note."
  echo "Carried: $count commits. Generated by \`nexus/gen-patches.sh\` from the \`Upstream-Status\` trailers; do not edit by hand."
  echo
  echo "Every fix is sent upstream. A row leaves this table when its upstream pull request is merged and the series is rebased past it."
  echo
  echo "| # | subject | upstream status |"
  echo "|---|---|---|"
  n=0
  for c in $commits; do
    n=$((n + 1))
    subject=$(git log -1 --format=%s "$c")
    status=$(git log -1 --format='%(trailers:key=Upstream-Status,valueonly)' "$c" | sed '/^$/d' | head -1)
    [ -n "$status" ] || { echo "error: $c ($subject) has no Upstream-Status trailer" >&2; exit 1; }
    printf '%s' "$status" | grep -Eq "$status_re" || { echo "error: $c ($subject) has a malformed Upstream-Status: '$status'" >&2; exit 1; }
    status=$(printf '%s' "$status" | sed -E "s|\[#([0-9]+)\]|[#\1]($upstream/pull/\1)|g")
    echo "| $n | $subject | $status |"
  done
} > PATCHES.md
echo "PATCHES.md: $count commits on ${base:0:8}"
